### ISSUE TITLE
state machine bug: calls shutdown if start fails

### ISSUE THREAD

**Issue by weissi** [swift-server/swift-service-lifecycle#103]
consider this code

```swift
        service.register(label: "thing",
                         start: .sync {
            print("THIS WILL FAIL")
            struct SomeError: Error {}
            throw SomeError()
        },
                         shutdown: .sync {
            print("SHUTDOWN <<< SHOULD NEVER HAPPEN")
        },
        shutdownIfNotStarted: false)

        try service.startAndWait()
```

clearly, it should never invoke the `shutdown` handler because the `start` one failed but it still will. It prints:

```
THIS WILL FAIL
SHUTDOWN <<< SHOULD NEVER HAPPEN
```

**Comment by tomerd** [comment]
@weissi iirc the design thought was that you may have created some state before failing that you want to clean up. obviously this is not always the case. is this behavior causing you issues? ideas on how to trade these off?

**Comment by weissi** [comment]
> @weissi iirc the design thought was that you may have created some state before failing that you want to clean up. obviously this is not always the case. is this behavior causing you issues? ideas on how to trade these off?

I thought the idea was that if you have created the state already, then you use `registerShutdown` which will unconditionally be called. But if you use `register(..., start:, shutdown:)` then I would've expected `shutdown` not to be called if `start` failed. Is there a situation where you would want `shutdown` to be called when `start` failed?

Especially given that I set `shutdownIfNotStarted: false` I _really_ wouldn't have expected it to shut down if `start` failed.
