### ISSUE TITLE
think about associated data when started

### ISSUE THREAD

**Issue by weissi** [swift-server/swift-service-lifecycle#11]
Manual state tracking has the advantage that you're able to associate data with a state. For example

```swift
enum LifecycleState {
    case stopped
    case started(Channel)
    case stopping(Channel)
}
```

migrating this to `Lifecycle` currently would require to add an optional

```
var serverChannel: Channel?
```

and then the code would start to contain `self.serverChannel!`. The other option is to duplicate the state tracking in `Lifecycle` as well as the application but that's not nice either because the states can get out of sync.

**Comment by rauhul** [comment]
As a new user to Lifecycle, I found the need to erase my EventLoopFuture<Channel> to EventLoopFuture<Void> a bit cumbersome/unintuitive. I had to store the result of start in a sideband promise so I could properly shutdown the Channel.

ex:
```swift
final class MetricsHTTPServer {
    let lifecycle = ComponentLifecycle(label: "foo")

    private(set) var channelPromise: EventLoopPromise<Channel>
    let eventLoopGroup: EventLoopGroup

    init(eventLoopGroup: EventLoopGroup) {
        self.eventLoopGroup = eventLoopGroup
        self.channelPromise = eventLoopGroup.next().makePromise(of: Channel.self)
        lifecycle.register(
            label: "Channel",
            start: .eventLoopFuture(self.start),
            shutdown: .eventLoopFuture(self.shutdown))
    }

    func start() -> EventLoopFuture<Void> {
        let bootstrap = ServerBootstrap(group: eventLoopGroup)
        // ...
        let future = bootstrap.bind(host: ..., port: ...)
        future.cascade(to: channelPromise)
        return future.map { _ in }
    }

    func shutdown() -> EventLoopFuture<Void> {
        return channelPromise.futureResult.flatMap { $0.close() }
    }
}
```

As a user, I would've preferred to defer the storage of the Channel to the ComponentLifecycle and have it passed back to me as part of the shutdown callback.

**Comment by weissi** [comment]
I don't think this is solved. What I was looking for is a way to (from the outside) access what the `start` method constructed.

**Comment by weissi** [comment]
For example, what I seem to always need is something like this:

```swift
        let service = ServiceLifecycle(configuration: .init(label: "proxy",
                                                            logger: logger,
                                                            callbackQueue: DispatchQueue.global(),
                                                            shutdownSignal: [.INT],
                                                            installBacktrace: true))
        var downstreamClient: Client?
        var otherComponent: Other?
        var proxy: ProxyServer?

        service.register(label: "downstream client",
                         start: .sync {
            downstreamClient = try Client()
        },
                         shutdown: .eventLoopFuture {
            downstreamClient!.shutdown()
        })

        service.register(label: "other",
                         start: .sync {
            other = try Other()
        },
                         shutdown: .eventLoopFuture {
            other!.shutdown()
        })

        service.register(label: "proxy",
                         start: .sync {
            proxy = try Proxy(downstream: downstreamClient!, other: other!)
        },
                         shutdown: .sync {
            try proxy!.syncShutdown()
        })

        try service.startAndWait()
    }
```

which seems very common but very ugly. The reason I want to use the `start` functionality is because if say the creation of `Other` fails, then `DownstreamClient` needs to be shut down (because it has been started before) but `Proxy` and `Other` don't (because they haven't been successfully started before).

**Comment by tomerd** [comment]
@weissi did you notice the new `registerStateful` methods? they allow start to return a state which is then handed off to the corresponding shutdown. this solves at least some of the use case?

**Comment by weissi** [comment]
@tomerd yes, I did. But I need what's returned from `start` for the first service in the `start` of the third service, not (exclusively) in the `shutdown`.

**Comment by tomerd** [comment]
@weissi see. in most cases that need something like this, I saw at the instance itself created outside the lifecycle call and the "starting" done in the start closure. e.g.

```
var downstreamClient = try Client()
let service = ServiceLifecycle(configuration: .init(label: "proxy",
                                                            logger: logger,
                                                            callbackQueue: DispatchQueue.global(),
                                                            shutdownSignal: [.INT],
                                                            installBacktrace: true))
       
        var otherComponent: Other?
        var proxy: ProxyServer?

        service.register(label: "downstream client",
                         start: .sync {
            downstreamClient.start()
        },
                         shutdown: .eventLoopFuture {
            downstreamClient.shutdown()
        })

        service.registerStateful(label: "proxy",
                         start: .sync {
            return try Proxy(downstream: downstreamClient)
        },
                         shutdown: .sync { proxy in
            try proxy.syncShutdown()
        })

        try service.startAndWait()
    }
```

That said, I can see how in some cases you would prefer to create the instance inside the start closure. Given that start is (at its core) an async operation, the ergonomics of returning values from the start method to the calling context is a bit tricky, but with a/a I can see how we make it nice. wdyt?

**Comment by weissi** [comment]
@tomerd Right, if everything does have `start` methods, then this works. Unfortunately, most things don't actually come with a `start` method (I guess it's because it's one extra thing for the user to do). If they don't have `start` methods, they normally require their dependencies to be passed into `init`.

Regarding how we'd surface "return" values from `start`: Yes, there's definitely an API design question on how we can square sync, callbacks, futures, a/a and surface the value to the next stages.

**Comment by FranzBusch** [comment]
Since we just changed the whole package to use a new Structured Concurrency approach, I would like to close this issue. @weissi Is that fine with you?

**Comment by weissi** [comment]
> Since we just changed the whole package to use a new Structured Concurrency approach, I would like to close this issue. @weissi Is that fine with you?

Yes
