### ISSUE TITLE
Fails to compile Xcode 13 RC (note: needs macOS release)

### ISSUE THREAD

**Issue by joshuawright11** [swift-server/swift-service-lifecycle#110]
Hey folks, trying to build with Xcode 13 RC.

### Steps to reproduce
`git clone https://github.com/swift-server/swift-service-lifecycle.git`
`cd swift-service-lifecycle`
`swift build`

```
.../swift-service-lifecycle/Sources/Lifecycle/Lifecycle.swift:16:8: error: no such module '_Concurrency'
import _Concurrency
```

And `swift --version` is
```
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
Target: x86_64-apple-macosx11.0
```

~Assume the fix is just to delete the `import _Concurrency`?~ (didn't actually fix it, as discussed below)

**Comment by ktoso** [comment]
Yeah, the import is not necessary anymore, do you want to send in a PR?

**Comment by ktoso** [comment]
Ok sorry I know what's going on now.

This is a weird situation in time where the RC of Xcode assumes that concurrency is provided by the OS -- the Betas did not assume that but this RC does. But the OS with Concurrency has not been released yet, so you can't use the RC Xcode yet.

This will just work once the next macOS is released, it will have the next SDK with concurrency and things will just work.

**Comment by joshuawright11** [comment]
Gotcha, okay. How does that work on linux I wonder? Is concurrency provided on the linux swift toolchains when >=5.5?

**Comment by ktoso** [comment]
On linux everything is included in the toolchains yes.

**Comment by joshuawright11** [comment]
👍 so just to be clear there is no way to use the new async await stuff with Xcode 13 RC until I've got macOS Monterey is installed?

(to use it I'd have to wait for Monterey to drop or use a prior Xcode 13 Beta)

**Comment by ktoso** [comment]
That seems to be the case AFAICS

**Comment by joshuawright11** [comment]
Since the official Xcode 13 is out and this still seems to prevent compilation for macOS targets other than the unreleased Monterrey, would it make more sense to instead of using

```swift
#if compiler(>=5.5)
```

use this?

```swift
#if canImport(_Concurrency)
```

Since technically using concurrency is dependent on the availability of the concurrency library rather than swift 5.5? And even after Monterrey is released compilation would still fail on older macOS targets. 

Perhaps it would also need to check for 5.5 as well;

```swift 
#if compiler(>=5.5) && canImport(_Concurrency)
```

The only thing I'm wondering is if `import _Concurrency` is going to stick around in future versions of Swift, rather than just be included in the language.

Regardless; I've opened a PR #111

**Comment by adam-fowler** [comment]
I've been able to get Xcode RC to work by installing the latest swift 5.5 nightly from swift.org.

**Comment by joshuawright11** [comment]
I assume that's because concurrency is included in the nightly toolchain?

**Comment by ktoso** [comment]
Commented in the PR; long story short:

```
#if compiler(>=5.5) && canImport(_Concurrency)
```

is the right way to guard _code using async/concurrency_, but...

> The only thing I'm wondering is if import _Concurrency is going to stick around in future versions of Swift, rather than just be included in the language.

I guess it'll stay but we should not "spell it out", it is imported automatically.

**Comment by joshuawright11** [comment]
Great, all merged so this can be closed.

@adam-fowler curious, were you able to get concurrency working with that nightly as well? I downloaded the last swift 5.5 nightly and still get a "async requires macOS 12" error when adding an async function. No error if I'm on trunk development snapshot, but I'd prefer to use Swift 5.5 bundled with concurrency.

**Comment by adam-fowler** [comment]
@joshuawright11  Yeah I've been running with RC for a while now with a swift 5.5 snapshot. Current one I am using 2021-09-15

**Comment by adam-fowler** [comment]
@joshuawright11 You do get a weird thing where the IDE tells you it won't compile, but when you build it, it does compile. It is probably easier to stick with the beta 5

**Comment by joshuawright11** [comment]
Ended up rolling with the latest nightly so I didn't need to sprinkle the `@available`s everywhere. Will wait to release until the concurrency back port work is widely available.
