### ISSUE TITLE
Logger argument missing in docs, or it should be an optional argument

### ISSUE THREAD

**Issue by tkrajacic** [swift-server/swift-service-lifecycle#139]
The Readme and docs ('How to adopt ServiceLifecycle in applications') have this exact same line
```swift
configuration: .init(gracefulShutdownSignals: [.sigterm])
```
which is missing the required argument `logger: Logger`.

We should either add the argument with a sample Logger to those three occurrences in the docs, or make the argument optional.

As per discussion with Fabian: /cc @FranzBusch

**Comment by FranzBusch** [comment]
Great catch thank you! Will get a PR up for this next week

**Comment by FranzBusch** [comment]
Just opened a PR to add the missing `logger` argument in the README. As far as I could see it was present in the other docs.

**Comment by tkrajacic** [comment]
It is missing in other places as well iiuc

https://github.com/search?q=repo%3Aswift-server%2Fswift-service-lifecycle%20init(gracefulShutdownSignals&type=code

**Comment by FranzBusch** [comment]
All these places do have the `logger` argument as far as I can see.
