### ISSUE TITLE
v1.0 alpha is reliant on Swift Backtrace

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/swift-service-lifecycle#159]
When Swift 5.9 is released swift-backtrace is no longer needed and is deprecated.
While v1.0.0-alpha.11 is not a full release many projects are still reliant on it. Is it possible to patch it to remove the backtrace install if compiling with Swift 5.9

**Comment by FranzBusch** [comment]
We can certainly cut a new 1.x release where we conditionally drop the dependency. Do you mind opening a PR for that?

**Comment by FranzBusch** [comment]
Going to close this now since we don't intend to ship another 1.x release
