### ISSUE TITLE
Question: return type of `cancelOnGracefulShutdown`

### ISSUE THREAD

**Issue by sidepelican** [swift-server/swift-service-lifecycle#179]
https://github.com/swift-server/swift-service-lifecycle/blob/f5780d95bdf3f740f14decb6c8c823815c883451/Sources/ServiceLifecycle/GracefulShutdown.swift#L118
I noticed that the `cancelOnGracefulShutdown` method signature suggests it returns an optional (`T?`). 
However, I couldn’t find any code paths in the implementation where a `nil` value would be returned.

Could you please clarify why the return type is optional in this context?
Is there a scenario where this method might return `nil` that I might have missed?

**Comment by FranzBusch** [comment]
You are right this seems like a mistake we should fix. This method indeed shouldn't return an optional. Would you be open to file a PR for this?
