### ISSUE TITLE
should be allow specifying a DispatchQueue per registered item?

### ISSUE THREAD

**Issue by weissi** [swift-server/swift-service-lifecycle#21]
Often, sub-systems won't be thread-safe so we rely on start & stop being called from the same thread. That is achievable with `Configuration` however only per `Lifecycle` and not once per item. What if two separate items rely on being each started/stopped on their own queue?

**Comment by FranzBusch** [comment]
Since we just changed the whole package to use a new Structured Concurrency approach, I would like to close this issue. @weissi Is that fine with you?
