### ISSUE TITLE
express backtrace as a LifecycleTask

### ISSUE THREAD

**Issue by tomerd** [swift-server/swift-service-lifecycle#35]
Should installing backtrace be expressed as a LifecycleTask which we automatically add when it's enabled

**Comment by hassila** [comment]
@tomerd should be sorted out with https://github.com/swift-server/swift-service-lifecycle/pull/87

**Comment by hassila** [comment]
I think this case can be closed after the discussion in #87 ?

**Comment by tomerd** [comment]
yes, I think backtraces are special enough so they should be installed as early as possible - at the init imo
