### ISSUE TITLE
Commit message template missing

### ISSUE THREAD

**Issue by florianreinhart** [swift-server/swift-service-lifecycle#61]
[CONTRIBUTING.md](https://github.com/swift-server/swift-service-lifecycle/blob/master/CONTRIBUTING.md#commit-message-template) refers to a commit message template at `dev/git.commit.template`. However, the file doesn't exist in this repo.

**Comment by ktoso** [comment]
Thanks for noticing!
It'd be the same as in https://github.com/apple/swift-nio/tree/master/dev

We could simply copy them over; would you be able to send in a PR please?
